In [1]:
from pyntcloud import PyntCloud
import pyvista as pv
anky = PyntCloud.from_file("result.ply")
anky.points

                 x          y            z        nx        ny        nz
0        -4.563625 -18.383928 -1204.598877 -0.020576 -0.214426 -0.976523
1        -4.714438 -18.498430 -1204.570557 -0.020576 -0.214426 -0.976523
2        -4.808158 -18.426062 -1204.584473 -0.020576 -0.214426 -0.976523
3        -4.714438 -18.498430 -1204.570557  0.282640 -0.564152 -0.775788
4        -4.563625 -18.383928 -1204.598877  0.282640 -0.564152 -0.775788
...            ...        ...          ...       ...       ...       ...
2327983  30.220774   5.658986 -1091.775269  0.151007  0.521150  0.840000
2327984  29.966265   5.453536 -1091.602051  0.151007  0.521150  0.840000
2327985  30.632772   5.581804 -1091.826416  0.203425  0.548379  0.811110
2327986  30.220774   5.658986 -1091.775269  0.203425  0.548379  0.811110
2327987  30.468969   5.342306 -1091.623413  0.203425  0.548379  0.811110

[2327988 rows x 6 columns]

In [7]:
anky_cloud = anky.get_sample("mesh_random", n=48000, rgb=False, normals=True, as_PyntCloud=True)
anky_cloud.to_file("seg1.pts",sep=" ",header=0,index=0)

In [4]:
anky_cloud = anky.get_sample("mesh_random", n=48000, rgb=False, normals=True, as_PyntCloud=True)
anky_cloud.to_file("SPAI-02-C2.pts",sep=" ",header=0,index=0)

In [6]:
from pyntcloud import PyntCloud
import pyvista as pv
import os

for file in os.listdir("SPAISTL"):
    name=file.split(".")
    anky = PyntCloud.from_file("SPAISTL/"+file)
    anky.points
    anky_cloud = anky.get_sample("mesh_random", n=48000, rgb=False, normals=True, as_PyntCloud=True)
    anky_cloud.to_file("SPAIPTS/"+name[0]+".pts",sep=" ",header=0,index=0)

In [2]:
from pyntcloud import PyntCloud
import pyvista as pv
import os

for file in os.listdir("C1_part_ply"):
    name=file.split(".")
    anky = PyntCloud.from_file("C1_part_ply/"+file)
    anky.points
    anky_cloud = anky.get_sample("mesh_random", n=48000, rgb=False, normals=True, as_PyntCloud=True)
    anky_cloud.to_file("C1_part_pts/"+name[0]+".pts",sep=" ",header=0,index=0)